[package]
name = "getuid"
version = "0.1.0"
authors = ["umaumax <umaumax7083@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
