[package]
name = "features-ex-lib"
version = "0.1.0"
authors = ["umaumax <umauma7083@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["hoge"]
hoge = []
fuga = []
piyo = []

[dependencies]
