[package]
name = "rusage_ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
nix = "0.24.1"
thiserror = "1.0.31"
threadpool = "1.8.1"
